version: '1.0'

stages:
- name: repo
  tasks:
  - get: repo
    params:
      depth: 3

- name: buildpack
  tasks:
  - aggregate:
      #- put: bp-backend
    - put: bp-frontend

- name: release
  tasks:
  - put: dicehub
    params:
      dice_yml: repo/dice.yml
      init_sql: repo/migrations
      replacement_images:
      - bp-backend/pack-result
      - bp-frontend/pack-result

- name: deploy
  tasks:
  - put: deploy
    params:
      time_out: 300

resources:
- name: repo
  type: git
  source:
    uri: ((gittar.repo))
    branch: ((gittar.branch))
    username: ((gittar.username))
    password: ((gittar.password))

- name: bp-backend
  type: buildpack
  source:
    context: repo/services/yankuang-equipment
    modules:
    - name: equipment-web
    - name: equipment-provider
      path: equipment-equipment-provider/equipment-equipment-provider-impl
    - name: syslog-provider
      path: equipment-syslog-provider/equipment-syslog-provider-impl
    - name: authority-provider
      path: equipment-authority-provider/equipment-authority-provider-impl

- name: bp-frontend
  type: buildpack
  source:
    context: repo/endpoints/yankuang-equipment-front
    modules:
    - name: yankuang-equipment-front

- name: dicehub
  type: dicehub
  source:
    workspace: ((dice.env))
    oss_endpoint: ((oss.endpoint))
    oss_access_key: ((oss.access.key))
    oss_secret_key: ((oss.secret.key))

- name: deploy
  type: dice
  source:
    app_id: ((dice.id))
    uri: ((dice.url))
    operator_id: ((dice.operator.id))
    workspace: ((dice.env))
    branch: ((gittar.branch))
